// Here are the Controllers methods for the GraphQL resolvers. These methods will be called when the corresponding GraphQL queries or mutations are executed. The actual implementation of these methods will depend on the business logic of your application and how you interact with your data sources (e.g., databases, external APIs, etc.). You can replace the panic statements with your actual logic to handle the requests and return the appropriate responses.
package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/keodevspace/movie-api/graph/model"
)

// AddMovie is the resolver for the addMovie field.
func (r *mutationResolver) AddMovie(ctx context.Context, input model.NewMovie) (*model.Movie, error) {
	panic(fmt.Errorf("not implemented: AddMovie - addMovie"))
}

// Movies is the resolver for the movies field.
func (r *queryResolver) Movies(ctx context.Context) ([]*model.Movie, error) {
	panic(fmt.Errorf("not implemented: Movies - movies"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
